### ISSUE TITLE
*Error in ResultReturner*

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/termux-api#34]
[tree/c553bc2ba7de37ad5c42df23d71e699d2785d7c5](https://github.com/termux/termux-api/tree/c553bc2ba7de37ad5c42df23d71e699d2785d7c5)

![image](https://github.com/user-attachments/assets/9d5a7ce7-cebb-4285-ad04-ae1f2f8ef81e)

![image](https://github.com/user-attachments/assets/4f9ba450-6184-4804-83db-a7e877e21a99)

I am pretty sure that I have an app up-to-date with last commit, see [termux/termux-api/pull/711](https://github.com/termux/termux-api/pull/711).

On my Fairphone 4 LineageOS but why?

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* termux-api application version:
* termux-api package version (installed through apt):
* Android OS version:
* Device model:

**Comment by Benjamin-Loison** [comment]
As I notifications capped to 50, I suspect `crontab` to be involved.

**Comment by Benjamin-Loison** [comment]
<details>
<summary><code>termux-plugin_execution_command.log</code>:</summary>

## Report Info


**User Action**: `plugin execution command`  
**Sender**: `ResultReturner`  
**Report Timestamp**: `2024-12-20 17:38:40.406 UTC`  
##

## Termux:API Error

```
Error in ResultReturner:
java.io.IOException: Connection refused
	at android.net.LocalSocketImpl.connectLocal(Native Method)
	at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:259)
	at android.net.LocalSocket.connect(LocalSocket.java:162)
	at com.termux.api.util.ResultReturner.lambda$returnData$0(ResultReturner.java:199)
	at com.termux.api.util.ResultReturner$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.lang.Thread.run(Thread.java:1012)

```



## Termux:API App Info (Current)

**APP_NAME**: `Termux:API`  
**PACKAGE_NAME**: `com.termux.api`  
**VERSION_NAME**: `0.50.1`  
**VERSION_CODE**: `51`  
**UID**: `10210`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `true`  
**SE_PROCESS_CONTEXT**: `u:r:untrusted_app_27:s0:c210,c256,c512,c768`  
**SE_FILE_CONTEXT**: `u:object_r:app_data_file:s0:c210,c256,c512,c768`  
**SE_INFO**: `default:targetSdkVersion=28:complete`  
**APK_RELEASE**: `Github`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`  
##


## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0+c2d57f2`  
**VERSION_CODE**: `118`  
**UID**: `10210`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `true`  
**SE_PROCESS_CONTEXT**: `u:r:untrusted_app_27:s0:c210,c256,c512,c768`  
**SE_FILE_CONTEXT**: `u:object_r:app_data_file:s0:c210,c256,c512,c768`  
**SE_INFO**: `default:targetSdkVersion=28:complete`  
**TERMUX_APP_PACKAGE_MANAGER**: -  
**TERMUX_APP_PACKAGE_VARIANT**: -  
**APK_RELEASE**: `Github`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`  
##


## Device Info

### Software

**OS_VERSION**: `4.19.322-perf-g1b745eae0308`  
**SDK_INT**: `34`  
**RELEASE**: `14`  
**ID**: `AP2A.240905.003`  
**DISPLAY**: `lineage_FP4-userdebug 14 AP2A.240905.003 5eb0466ea7`  
**INCREMENTAL**: `5eb0466ea7`  
**SECURITY_PATCH**: `2024-12-01`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `userdebug`  
**TAGS**: `release-keys`  
**MAX_PHANTOM_PROCESSES**: - (*Requires `DUMP` and `PACKAGE_USAGE_STATS` permission*)  
**MONITOR_PHANTOM_PROCS**: `false`  
**DEVICE_CONFIG_SYNC_DISABLED**: -  

### Hardware

**MANUFACTURER**: `Fairphone`  
**BRAND**: `Fairphone`  
**MODEL**: `FP4`  
**PRODUCT**: `FP4eea`  
**BOARD**: `FP4`  
**HARDWARE**: `qcom`  
**DEVICE**: `FP4`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##
</details>

**Comment by Benjamin-Loison** [comment]
APT packages are up-to-date. What about Termux itself?

**Comment by Benjamin-Loison** [comment]
![image](https://github.com/user-attachments/assets/c372c083-9508-4c4a-a8c1-4a54c0a8d018)

**Comment by Benjamin-Loison** [comment]
Search upstream and when issue is actually happening (`ps aux`, `crontab` and `~/.termux/boot/start.sh`).

Precisely when occurred the first error?
People upstream also mention that it happens randomly.
Termux jobs cheduler investigate.
Update LineageOS. Now done.

Search other issues and pull requests mentioning `ResultReturner`.

https://github.com/termux/termux-api/issues/573
https://github.com/termux/termux-api/issues/607

**Comment by Benjamin-Loison** [comment]
Maybe related to #56.

**Comment by Benjamin-Loison** [comment]
@iamgitcat Thanks for your input, I'll try to reproduce your issue when I'll face this error again.

**Comment by Benjamin-Loison** [comment]
<details>
<summary>Faced on my Fairphone 4 LineageOS 23.2 with <code>termux-location</code>:</summary>

## Report Info


**User Action**: `plugin execution command`  
**Sender**: `ResultReturner`  
**Report Timestamp**: `2026-03-08 17:20:21.782 UTC`  
##

## Termux:API Error

```
Error in ResultReturner:
java.io.IOException: Connection refused
	at android.net.LocalSocketImpl.connectLocal(Native Method)
	at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:259)
	at android.net.LocalSocket.connect(LocalSocket.java:162)
	at com.termux.api.util.ResultReturner.lambda$returnData$0(ResultReturner.java:250)
	at com.termux.api.util.ResultReturner$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1563)
	Suppressed: java.lang.Exception: Called by:
		at com.termux.api.util.ResultReturner.returnData(ResultReturner.java:239)
		at com.termux.api.apis.LocationAPI.onReceive(LocationAPI.java:35)
		at com.termux.api.TermuxApiReceiver.doWork(TermuxApiReceiver.java:158)
		at com.termux.api.TermuxApiReceiver.onReceive(TermuxApiReceiver.java:66)
		at android.app.ActivityThread.handleReceiver(ActivityThread.java:5301)
		at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2715)
		at android.os.Handler.dispatchMessage(Handler.java:132)
		at android.os.Looper.dispatchMessage(Looper.java:333)
		at android.os.Looper.loopOnce(Looper.java:263)
		at android.os.Looper.loop(Looper.java:367)
		at android.app.ActivityThread.main(ActivityThread.java:9287)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:566)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:929)

```



## Termux:API App Info (Current)

**APP_NAME**: `Termux:API`  
**PACKAGE_NAME**: `com.termux.api`  
**VERSION_NAME**: `0.53.0`  
**VERSION_CODE**: `1002`  
**UID**: `10187`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `true`  
**SE_PROCESS_CONTEXT**: `u:r:untrusted_app_27:s0:c187,c256,c512,c768`  
**SE_FILE_CONTEXT**: `u:object_r:app_data_file:s0:c187,c256,c512,c768`  
**SE_INFO**: `default:targetSdkVersion=28:complete`  
**APK_RELEASE**: `Github`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`  
##


## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0+3f0dec3`  
**VERSION_CODE**: `118`  
**UID**: `10187`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `true`  
**SE_PROCESS_CONTEXT**: `u:r:untrusted_app_27:s0:c187,c256,c512,c768`  
**SE_FILE_CONTEXT**: `u:object_r:app_data_file:s0:c187,c256,c512,c768`  
**SE_INFO**: `default:targetSdkVersion=28:complete`  
**TERMUX_APP_PACKAGE_MANAGER**: -  
**TERMUX_APP_PACKAGE_VARIANT**: -  
**APK_RELEASE**: `Github`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`  
##


## Device Info

### Software

**OS_VERSION**: `4.19.325-cip128-st12-perf-g6ec2fe2d2a1f`  
**SDK_INT**: `36`  
**RELEASE**: `16`  
**ID**: `BP4A.251205.006`  
**DISPLAY**: `BP4A.251205.006`  
**INCREMENTAL**: `1be9a6cac3`  
**SECURITY_PATCH**: `2026-02-01`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `userdebug`  
**TAGS**: `release-keys`  
**MAX_PHANTOM_PROCESSES**: - (*Requires `DUMP` and `PACKAGE_USAGE_STATS` permission*)  
**MONITOR_PHANTOM_PROCS**: `false`  
**DEVICE_CONFIG_SYNC_DISABLED**: -  

### Hardware

**MANUFACTURER**: `Fairphone`  
**BRAND**: `Fairphone`  
**MODEL**: `FP4`  
**PRODUCT**: `FP4eea`  
**BOARD**: `FP4`  
**HARDWARE**: `qcom`  
**DEVICE**: `FP4`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##
</details>

**Comment by Benjamin-Loison** [comment]
Would help [Benjamin_Loison/Voice_assistant/issues/33](https://codeberg.org/Benjamin_Loison/Voice_assistant/issues/33).
